version: '3'
services:
  neo4j:
    image: neo4j:3.4
    hostname: neo4j
    container_name: neo4j
    ports:
    - "7474:7474"
    - "7687:7687"
    volumes:
    - ./neo4j/conf:/conf
    - ./neo4j/data:/data
    - ./neo4j/logs:/logs
    - ./neo4j/plugins:/plugins
    environment:
    - NEO4J_AUTH=neo4j/test123



# version: '3'
# services:
#   neo4j:
#     image: neo4j:3.4
#     hostname: neo4j
#     container_name: neo4j
#     ports:
#     - "7474:7474"
#     - "7687:7687"
#     depends_on:
#     - kafka
#     volumes:
#     - ./neo4j/conf:/conf
#     - ./neo4j/data:/data
#     - ./neo4j/logs:/logs
#     - ./neo4j/plugins:/plugins
#     environment:
#       NEO4J_AUTH: neo4j/streams
#       NEO4J_dbms_logs_debug_level: DEBUG
#       # KAFKA related configuration
#       NEO4J_kafka_zookeeper_connect: zookeeper:12181
#       NEO4J_kafka_bootstrap_servers: kafka:19092